version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile
    container_name: client-dev-container
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:


